# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-12-03 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '__first__'),
        ('blog', '0002_auto_20211029_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grades.Grade'),
        ),
    ]
