# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-12-03 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='grades.Grade'),
        ),
    ]
