# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-12-03 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='level',
            field=models.CharField(choices=[(1, 'الإبتدائي'), (2, 'المتوسط'), (3, 'الثانوي')], default=3, max_length=1),
        ),
    ]
