# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marks',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Marks'},
        ),
    ]
